### ISSUE TITLE
Browser link crashing with VS 16.3 preview 2 and/or dotnet core 3 preview 8

### ISSUE THREAD

**Issue by nrandell** [aspnet/BrowserLink#102]
This was working yesterday (16.3 preview 1) and dotnet core 3 preview 7, even though the app is a 2.2 app.

Start up the web site, all ok. 
Attach a browser, all starts off ok.
Then visual studio crashes and closes.

The event viewer shows the following which makes me think it is BrowserLink
```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.WebTools.Shared.Web.VS.Helpers.VsWebUrlUtil.GetVsWebUrlFromUrlServiceUsingUrl(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.Uri, Microsoft.WebTools.Shared.VS.Helpers.ILocationContainer ByRef)
   at Microsoft.WebTools.Shared.Web.VS.Helpers.VsWebUrlUtil.GetVsWebUrlFromUrl(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.Uri)
   at Microsoft.WebTools.Shared.Web.VS.Helpers.WebUrlLocationContainerService.GetVsWebUrlFromUrl(Microsoft.VisualStudio.Shell.Interop.IVsHierarchy, System.Uri)
   at Microsoft.WebTools.Shared.VS.Helpers.LazyLocationContainer+LazyLocationContainerFromUrl.CreateActualLocationContainer()
   at Microsoft.WebTools.Shared.VS.Helpers.LazyLocationContainer.GetAppRelativeUrl(System.Uri ByRef)
   at Microsoft.WebTools.Shared.VS.Helpers.DocumentLocation.Microsoft.WebTools.Shared.VS.Helpers.IDocumentLocation.GetAppRelativeUrl(System.Uri ByRef)
   at Microsoft.WebTools.BrowserLink.Package.FetchedDocument..ctor(Microsoft.VisualStudio.Shell.Interop.IVsSolution, System.Uri, System.String, System.String, System.Net.HttpStatusCode)
   at Microsoft.WebTools.BrowserLink.Package.FetchedDocumentUtilities+<CreateBasicFetchedDocument>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.WebTools.BrowserLink.SourceMappingExtension+<OnConnected>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)


```

The same project in VS 16.2 works ok.

**Comment by nrandell** [comment]
This looks like a bug that has been fixed in visual studio 16.4 preview 2. See https://developercommunity.visualstudio.com/content/problem/756700/browserlink-crashes-visual-studio-in-aspnet-core-3.html for more details
